[versions]
#noinspection UnusedVersionCatalogEntry
compileSdk = "36"
#noinspection UnusedVersionCatalogEntry
minSdk = "28"
#noinspection UnusedVersionCatalogEntry
targetSdk = "35"

agp = "8.13.1"
androidTools = "31.13.1"
androidDesugarJdkLibs = "2.1.5"
androidxActivity = "1.12.0"
androidxAppcompat = "1.7.1"
androidxComposeBom = "2025.11.01"
androidxConstraintLayoutCompose = "1.1.1"
assertk="0.28.1"
assertkLint="1.5.1"
googleAccompanist = "0.36.0"
kotlin="2.2.21"
kotlinxCoroutines = "1.10.2"
#noinspection UnusedVersionCatalogEntry
ktfmt = "0.59"
slackComposeLintChecks = "1.4.2"

[libraries]
accompanistDrawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "googleAccompanist" }
#noinspection UnusedVersionCatalogEntry
accompanistSystemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "googleAccompanist" }
androidDesugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidxComposeActivity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
#noinspection UnusedVersionCatalogEntry
androidxComposeConstraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidxConstraintLayoutCompose" }
#noinspection UnusedVersionCatalogEntry
androidxComposeMaterialIcons = { group = "androidx.compose.material", name = "material-icons-core" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
#noinspection UnusedVersionCatalogEntry
androidxComposeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }
#noinspection UnusedVersionCatalogEntry
assertkLint = { group = "com.jzbrooks", name = "assertk-lint", version.ref = "assertkLint" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
#noinspection UnusedVersionCatalogEntry
slackComposeLintChecks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "slackComposeLintChecks" }

# Dependencies of the included build-logic
androidGradleApiPlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
androidToolsCommon = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
composeGradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

[plugins]
agpApp = { id = "com.android.application", version.ref = "agp" }
agpLibrary = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# internal convention plugins defined in build-logic:
cfaAndroidLibrary = { id = "cfa.android.library" }
cfaAndroidLibraryCompose = { id = "cfa.android.library.compose" }
